export const recipes = [
  {
    id: 11,
    slug: "pasta-bolonese",
    title: "Паста Болоньезе",
    kcal: 550,
    ingredients: [
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 2, item: "Сливки", img: "/img/cream.jpg" },
      { id: 4, item: "Спагетти", img: "/img/spaghetti.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
    ],
    img: "/img/bolonese.jpg",
  },
  {
    id: 22,
    slug: "salat-sezar",
    title: "Салат Цезарь",
    kcal: 400,
    ingredients: [
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
      { id: 12, item: "Салат романо", img: "/img/romano.jpg" },
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
    ],
    img: "/img/salat-cezar.jpg",
  },
  {
    id: 33,
    slug: "pirog",
    title: "Простой пирог с творогом",
    kcal: 700,
    ingredients: [
      { id: 9, item: "Творог", img: "/img/tvorog.jpg" },
      { id: 2, item: "Сливки", img: "/img/cream.jpg" },
      { id: 8, item: "Мука", img: "/img/muka.jpeg" },
      { id: 13, item: "Сахар", img: "/img/romano.jpg" },
    ],
    img: "/img/pie.jpg",
  },
  {
    id: 44,
    slug: "burger",
    title: "Бургер Техас",
    kcal: 1100,
    ingredients: [
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 12, item: "Салат романо", img: "/img/romano.jpg" },
      { id: 11, item: "Говядина", img: "/img/beef.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
    ],
    img: "/img/texas.jpg",
  },
  {
    id: 55,
    slug: "yaichnitsa",
    title: "Яичница",
    kcal: 200,
    ingredients: [
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "/img/eggs.jpg",
  },
];
