export const recipes = [
  {
    id: 11,
    slug: "pasta-bolonese",
    title: "Паста Болоньезе",
    kcal: 550,
    ingredients: [
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 2, item: "Сливки", img: "/img/cream.jpg" },
      { id: 4, item: "Спагетти", img: "/img/spaghetti.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "/img/bolonese.jpg",
  },
  {
    id: 22,
    slug: "salat-sezar",
    title: "Салат Цезарь",
    kcal: 400,
    ingredients: [
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
      { id: 12, item: "Салат романо", img: "/img/romano.jpg" },
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "/img/salat-cezar.jpg",
  },
  {
    id: 33,
    slug: "pirog",
    title: "Простой пирог с творогом",
    kcal: 700,
    ingredients: [
      { id: 9, item: "Творог", img: "/img/tvorog.jpg" },
      { id: 2, item: "Сливки", img: "/img/cream.jpg" },
      { id: 8, item: "Мука", img: "/img/muka.jpeg" },
      { id: 13, item: "Сахар", img: "/img/romano.jpg" },
    ],
    img: "/img/pie.jpg",
  },
  {
    id: 44,
    slug: "burger",
    title: "Бургер Техас",
    kcal: 1100,
    ingredients: [
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 12, item: "Салат романо", img: "/img/romano.jpg" },
      { id: 11, item: "Говядина", img: "/img/beef.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
    ],
    img: "/img/texas.jpg",
  },
  {
    id: 55,
    slug: "yaichnitsa",
    title: "Яичница",
    kcal: 200,
    ingredients: [
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "/img/eggs.jpg",
  },
  {
    id: 66,
    slug: "pirog--s-kyritsey",
    title: "Пирог с курицей",
    kcal: 700,
    ingredients: [
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 8, item: "Мука", img: "/img/muka.jpeg" },
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
    ],
    img: "/img/kuritsa_syr-scaled.jpg",
  },
  {
    id: 77,
    slug: "kyritsa-zapechenaya-pod-sirom",
    title: "Курица запеченная под сыром",
    kcal: 350,
    ingredients: [
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
    ],
    img: "/img/kyritsa-sir.jpg",
  },
  {
    id: 88,
    slug: "salat-grecheskiy",
    title: "Салат Греческий",
    kcal: 180,
    ingredients: [
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 12, item: "Салат романо", img: "/img/romano.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
    ],
    img: "/img/grecheskiy.jpg",
  },
  {
    id: 99,
    slug: "pasta-s-kyritsey",
    title: "Паста с курицей",
    kcal: 380,
    ingredients: [
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
    ],
    img: "",
  },
  {
    id: 1010,
    slug: "ydon-s-govyadinoy",
    title: "Удон с говядиной",
    kcal: 480,
    ingredients: [
      { id: 11, item: "Говядина", img: "/img/beef.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
    ],
    img: "",
  },
  {
    id: 1111,
    slug: "omlet-s-sirom",
    title: "Омлет с сыром и помидорами",
    kcal: 320,
    ingredients: [
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 2, item: "Сливки", img: "/img/cream.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "",
  },
  {
    id: 1212,
    slug: "kotlety-iz-kuritsy",
    title: "Котлеты из курицы",
    kcal: 280,
    ingredients: [
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
      { id: 8, item: "Мука", img: "/img/muka.jpeg" },
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "",
  },
  {
    id: 1313,
    slug: "pitstsa-s-govyadinoy",
    title: "Пицца с говядиной",
    kcal: 650,
    ingredients: [
      { id: 8, item: "Мука", img: "/img/muka.jpeg" },
      { id: 11, item: "Говядина", img: "/img/beef.jpg" },
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 7, item: "Сыр", img: "/img/swiss.jpg" },
      { id: 5, item: "Лук", img: "/img/onion.png" },
    ],
    img: "",
  },
  {
    id: 1414,
    slug: "bliny-s-tvorogom",
    title: "Блины с творогом",
    kcal: 420,
    ingredients: [
      { id: 8, item: "Мука", img: "/img/muka.jpeg" },
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 9, item: "Творог", img: "/img/tvorog.jpg" },
      { id: 2, item: "Сливки", img: "/img/cream.jpg" },
      { id: 13, item: "Сахар", img: "/img/romano.jpg" },
    ],
    img: "",
  },
  {
    id: 1515,
    slug: "salat-s-kuritsey-i-yaytsom",
    title: "Салат с курицей и яйцом",
    kcal: 250,
    ingredients: [
      { id: 6, item: "Курица", img: "/img/chicken.jpg" },
      { id: 3, item: "Яйцо", img: "/img/egg.jpg" },
      { id: 12, item: "Салат романо", img: "/img/romano.jpg" },
      { id: 1, item: "Томат", img: "/img/tomato.jpg" },
      { id: 10, item: "Соль", img: "/img/chicken.jpg" },
    ],
    img: "",
  },
];
