-- ============================================================
-- Инициализация: таблицы + RLS + наполнение (13 ингредиентов, 15 рецептов)
-- ============================================================

-- Ингредиенты
create table public.ingredients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  img_url text
);

-- Рецепты (author_id — резерв под будущую авторизацию)
create table public.recipes (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  kcal int not null default 0,
  img_url text,
  author_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- Связь рецепт <-> ингредиент
create table public.recipe_ingredients (
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  ingredient_id bigint not null references public.ingredients(id) on delete cascade,
  primary key (recipe_id, ingredient_id)
);

-- Индекс для поиска рецептов по ингредиентам
create index recipe_ingredients_ingredient_idx on public.recipe_ingredients (ingredient_id);

-- ============================================================
-- RLS: публичное чтение, запись — только вручную (дашборд / secret key)
-- ============================================================
alter table public.ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;

grant select on public.ingredients to anon, authenticated;
grant select on public.recipes to anon, authenticated;
grant select on public.recipe_ingredients to anon, authenticated;

create policy "ingredients are publicly viewable"
  on public.ingredients
  for select
  using (true);

create policy "recipes are publicly viewable"
  on public.recipes
  for select
  using (true);

create policy "recipe_ingredients are publicly viewable"
  on public.recipe_ingredients
  for select
  using (true);

-- ============================================================
-- Наполнение
-- ============================================================
insert into public.ingredients (id, name, img_url) values
  (1,  'Томат',         '/img/tomato.jpg'),
  (2,  'Сливки',        '/img/cream.jpg'),
  (3,  'Яйцо',          '/img/egg.jpg'),
  (4,  'Спагетти',      '/img/spaghetti.jpg'),
  (5,  'Лук',           '/img/onion.png'),
  (6,  'Курица',        '/img/chicken.jpg'),
  (7,  'Сыр',           '/img/swiss.jpg'),
  (8,  'Мука',          '/img/muka.jpeg'),
  (9,  'Творог',        '/img/tvorog.jpg'),
  (10, 'Соль',          '/img/chicken.jpg'),
  (11, 'Говядина',      '/img/beef.jpg'),
  (12, 'Салат романо',  '/img/romano.jpg'),
  (13, 'Сахар',         '/img/romano.jpg')
on conflict (id) do nothing;

insert into public.recipes (id, slug, title, kcal, img_url) values
  (11,  'pasta-bolonese',              'Паста Болоньезе',              550,  '/img/bolonese.jpg'),
  (22,  'salat-sezar',                 'Салат Цезарь',                 400,  '/img/salat-cezar.jpg'),
  (33,  'pirog',                       'Простой пирог с творогом',     700,  '/img/pie.jpg'),
  (44,  'burger',                      'Бургер Техас',                 1100, '/img/texas.jpg'),
  (55,  'yaichnitsa',                  'Яичница',                      200,  '/img/eggs.jpg'),
  (66,  'pirog--s-kyritsey',           'Пирог с курицей',              700,  null),
  (77,  'kyritsa-zapechenaya-pod-sirom','Курица запеченная под сыром',  350,  null),
  (88,  'salat-grecheskiy',            'Салат Греческий',              180,  null),
  (99,  'pasta-s-kyritsey',            'Паста с курицей',              380,  null),
  (1010,'ydon-s-govyadinoy',           'Удон с говядиной',             480,  null),
  (1111,'omlet-s-sirom',               'Омлет с сыром и помидорами',   320,  null),
  (1212,'kotlety-iz-kuritsy',          'Котлеты из курицы',            280,  null),
  (1313,'pitstsa-s-govyadinoy',        'Пицца с говядиной',            650,  null),
  (1414,'bliny-s-tvorogom',            'Блины с творогом',             420,  null),
  (1515,'salat-s-kuritsey-i-yaytsom',  'Салат с курицей и яйцом',      250,  null)
on conflict (id) do nothing;

insert into public.recipe_ingredients (recipe_id, ingredient_id) values
  (11,  1),(11,  2),(11,  4),(11,  5),(11,  7),(11, 10),
  (22,  1),(22,  7),(22, 12),(22,  6),(22, 10),
  (33,  9),(33,  2),(33,  8),(33, 13),
  (44,  1),(44, 12),(44, 11),(44,  5),(44, 10),(44,  7),
  (55,  3),(55, 10),
  (66,  3),(66,  5),(66,  8),(66,  6),
  (77,  5),(77,  6),(77,  7),(77,  1),
  (88,  5),(88,  1),(88, 12),(88,  7),
  (99,  5),(99,  6),(99,  7),
  (1010,11),(1010, 5),(1010,10),(1010, 3),
  (1111, 3),(1111, 7),(1111, 1),(1111, 2),(1111,10),
  (1212, 6),(1212, 5),(1212, 8),(1212, 3),(1212,10),
  (1313, 8),(1313,11),(1313, 1),(1313, 7),(1313, 5),
  (1414, 8),(1414, 3),(1414, 9),(1414, 2),(1414,13),
  (1515, 6),(1515, 3),(1515,12),(1515, 1),(1515,10)
on conflict (recipe_id, ingredient_id) do nothing;
